### ISSUE TITLE
Don't install

### ISSUE THREAD

**Issue by IgorDePaula** [geekcom/php-extension-hello#1]
![Captura de tela de 2019-12-27 14-10-41](https://user-images.githubusercontent.com/2833993/71525902-bab5fc80-28b2-11ea-8d76-9555e88d2026.png)

![Captura de tela de 2019-12-27 14-10-47](https://user-images.githubusercontent.com/2833993/71525910-c5709180-28b2-11ea-88d0-0cb7c0a4a669.png)

**Comment by geekcom** [comment]
Ops:

* phpize
* `./configure --with-php-config=/usr/local/bin/php-config`
* make
* make install
* `php -d extension=hello.so -r 'hello();'`

**Comment by IgorDePaula** [comment]
![Captura de tela de 2019-12-27 17-08-13](https://user-images.githubusercontent.com/2833993/71530998-7edb6100-28cb-11ea-9b78-e2a754d4feed.png)

**Comment by geekcom** [comment]
updated

`./configure`

**Comment by IgorDePaula** [comment]
Yes, now its works.
